# Cleaning Employee Exit Surveys

In this lab, you'll clean exit surveys from employees of the [Department of Education, Training and Employment (DETE)](https://en.wikipedia.org/wiki/Department_of_Education_and_Training_(Queensland)}) and the Technical and Further Education (TAFE) body of the Queensland government in Australia. The TAFE exit survey can be found [here](https://data.gov.au/dataset/ds-qld-89970a3b-182b-41ea-aea2-6f9f17b5907e/details?q=exit%20survey) and the survey for the DETE can be found [here](https://data.gov.au/dataset/ds-qld-fe96ff30-d157-4a81-851d-215f2a0fe26d/details?q=exit%20survey).

Complete the tasks listed below. You can submit the completed lab until 11:59 PM in the night.

<u>Requirement:</u><br>
Do your best to write Pythonic code instead of the traditional programming code.

<u>Hint:</u><br>
For all of these tasks, you would need to read the data first using __pd.read_csv__

### Task 1 (2 marks)

Import the necessary libraries, read the data __dete_survey.csv__ as well as __tafe_survey.csv__, and ensure that the columns are not truncated (that is, by default pandas shows only the first few columns followed by ellipsis followed by the last few columns).

<u>Hint:</u> pd.options...

Once you have done that, output some information about your columns such as how many columns are there, the data types of the columns etc.

In [1]:
### Write your code below this comment.
import pandas as pd

del_sur=pd.read_csv('/content/dete_survey.csv')
tafe_sur=pd.read_csv('/content/tafe_survey.csv')

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
del_sur

,ID,SeparationType,Cease Date,DETE Start Date,Role Start Date,Position,Classification,Region,Business Unit,Employment Status,Career move to public sector,Career move to private sector,Interpersonal conflicts,Job dissatisfaction,Dissatisfaction with the department,Physical work environment,Lack of recognition,Lack of job security,Work location,Employment conditions,Maternity/family,Relocation,Study/Travel,Ill Health,Traumatic incident,Work life balance,Workload,None of the above,Professional Development,Opportunities for promotion,Staff morale,Workplace issue,Physical environment,Worklife balance,Stress and pressure support,Performance of supervisor,Peer support,Initiative,Skills,Coach,Career Aspirations,Feedback,Further PD,Communication,My say,Information,Kept informed,Wellness programs,Health & Safety,Gender,Age,Aboriginal,Torres Strait,South Sea,Disability,NESB
0,1,Ill Health Retirement,08/2012,1984,2004,Public Servant,A01-A04,Central Office,Corporate Strategy and Peformance,Permanent Full-time,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,True,A,A,N,N,N,A,A,A,A,N,N,N,A,A,A,N,A,A,N,N,N,Male,56-60,NaN,NaN,NaN,NaN,Yes
1,2,Voluntary Early Retirement (VER),08/2012,Not Stated,Not Stated,Public Servant,AO5-AO7,Central Office,Corporate Strategy and Peformance,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,A,A,N,N,N,N,A,A,A,N,N,N,A,A,A,N,A,A,N,N,N,Male,56-60,NaN,NaN,NaN,NaN,NaN
2,3,Voluntary Early Retirement (VER),05/2012,2011,2011,Schools Officer,NaN,Central Office,Education Queensland,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,A,A,N,N,N,N,Male,61 or older,NaN,NaN,NaN,NaN,NaN
3,4,Resignation-Other reasons,05/2012,2005,2006,Teacher,Primary,Central Queensland,NaN,Permanent Full-time,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,A,N,N,N,A,A,N,N,A,A,A,A,A,A,A,A,A,A,A,N,A,Female,36-40,NaN,NaN,NaN,NaN,NaN
4,5,Age Retirement,05/2012,1970,1989,Head of Curriculum/Head of Special Education,NaN,South East,NaN,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,A,A,N,N,D,D,N,A,A,A,A,A,A,SA,SA,D,D,A,N,A,M,Female,61 or older,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,819,Age Retirement,02/2014,1977,1999,Teacher,Primary,Central Queensland,NaN,Permanent Part-time,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,SA,N,D,D,A,N,N,D,A,N,A,A,N,SA,SA,N,D,A,A,A,SA,Female,56-60,NaN,NaN,NaN,NaN,NaN
818,820,Age Retirement,01/2014,1980,1980,Teacher,Secondary,North Coast,NaN,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,A,SA,D,D,D,A,A,N,A,N,A,A,N,A,N,N,A,A,N,N,N,Male,51-55,NaN,NaN,NaN,NaN,NaN
819,821,Resignation-Move overseas/interstate,01/2014,2009,2009,Public Servant,A01-A04,Central Office,Education Queensland,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,False,A,A,A,A,A,D,N,A,A,A,A,A,A,A,A,A,A,A,A,N,A,Female,31-35,NaN,NaN,NaN,NaN,NaN
820,822,Ill Health Retirement,12/2013,2001,2009,Teacher,Secondary,Darling Downs South West,NaN,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,A,D,D,A,SD,SD,SD,A,D,SD,SD,D,A,A,N,N,N,SD,A,N,A,Female,41-45,NaN,NaN,NaN,NaN,NaN
821,823,Resignation-Move overseas/interstate,12/2013,Not Stated,Not Stated,Teacher Aide,NaN,Metropolitan,NaN,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
tafe_sur

,Record ID,Institute,WorkArea,CESSATION YEAR,Reason for ceasing employment,Contributing Factors. Career Move - Public Sector,Contributing Factors. Career Move - Private Sector,Contributing Factors. Career Move - Self-employment,Contributing Factors. Ill Health,Contributing Factors. Maternity/Family,Contributing Factors. Dissatisfaction,Contributing Factors. Job Dissatisfaction,Contributing Factors. Interpersonal Conflict,Contributing Factors. Study,Contributing Factors. Travel,Contributing Factors. Other,Contributing Factors. NONE,Main Factor. Which of these was the main factor for leaving?,InstituteViews. Topic:1. I feel the senior leadership had a clear vision and direction,InstituteViews. Topic:2. I was given access to skills training to help me do my job better,InstituteViews. Topic:3. I was given adequate opportunities for personal development,InstituteViews. Topic:4. I was given adequate opportunities for promotion within %Institute]Q25LBL%,InstituteViews. Topic:5. I felt the salary for the job was right for the responsibilities I had,InstituteViews. Topic:6. The organisation recognised when staff did good work,InstituteViews. Topic:7. Management was generally supportive of me,InstituteViews. Topic:8. Management was generally supportive of my team,InstituteViews. Topic:9. I was kept informed of the changes in the organisation which would affect me,InstituteViews. Topic:10. Staff morale was positive within the Institute,InstituteViews. Topic:11. If I had a workplace issue it was dealt with quickly,InstituteViews. Topic:12. If I had a workplace issue it was dealt with efficiently,InstituteViews. Topic:13. If I had a workplace issue it was dealt with discreetly,WorkUnitViews. Topic:14. I was satisfied with the quality of the management and supervision within my work unit,WorkUnitViews. Topic:15. I worked well with my colleagues,WorkUnitViews. Topic:16. My job was challenging and interesting,WorkUnitViews. Topic:17. I was encouraged to use my initiative in the course of my work,WorkUnitViews. Topic:18. I had sufficient contact with other people in my job,WorkUnitViews. Topic:19. I was given adequate support and co-operation by my peers to enable me to do my job,WorkUnitViews. Topic:20. I was able to use the full range of my skills in my job,WorkUnitViews. Topic:21. I was able to use the full range of my abilities in my job. ; Category:Level of Agreement; Question:YOUR VIEWS ABOUT YOUR WORK UNIT],WorkUnitViews. Topic:22. I was able to use the full range of my knowledge in my job,WorkUnitViews. Topic:23. My job provided sufficient variety,WorkUnitViews. Topic:24. I was able to cope with the level of stress and pressure in my job,WorkUnitViews. Topic:25. My job allowed me to balance the demands of work and family to my satisfaction,WorkUnitViews. Topic:26. My supervisor gave me adequate personal recognition and feedback on my performance,"WorkUnitViews. Topic:27. My working environment was satisfactory e.g. sufficient space, good lighting, suitable seating and working area",WorkUnitViews. Topic:28. I was given the opportunity to mentor and coach others in order for me to pass on my skills and knowledge prior to my cessation date,WorkUnitViews. Topic:29. There was adequate communication between staff in my unit,WorkUnitViews. Topic:30. Staff morale was positive within my work unit,Induction. Did you undertake Workplace Induction?,InductionInfo. Topic:Did you undertake a Corporate Induction?,InductionInfo. Topic:Did you undertake a Institute Induction?,InductionInfo. Topic: Did you undertake Team Induction?,InductionInfo. Face to Face Topic:Did you undertake a Corporate Induction; Category:How it was conducted?,InductionInfo. On-line Topic:Did you undertake a Corporate Induction; Category:How it was conducted?,InductionInfo. Induction Manual Topic:Did you undertake a Corporate Induction?,InductionInfo. Face to Face Topic:Did you undertake a Institute Induction?,InductionInfo. On-line Topic:Did you undertake a Institute Induction?,InductionInfo. Induction Manual Topic:Did you undertake a Institute Induction?,InductionInfo. Face to Face Topic: Did you undertake Team Induction; Category?,InductionInfo. On-line Topic: Did you undertake Team Induction?process you undertook and how it was conducted.],InductionInfo. Induction Manual Topic: Did you undertake Team Induction?,Workplace. Topic:Did you and your Manager develop a Performance and Professional Development Plan (PPDP)?,Workplace. Topic:Does your workplace promote a work culture free from all forms of unlawful discrimination?,Workplace. Topic:Does your workplace promote and practice the principles of employment equity?,Workplace. Topic:Does your workplace value the diversity of its employees?,Workplace. Topic:Would you recommend the Institute as an employer to others?,Gender. What is your Gender?,CurrentAge. Current Age,Employment Type. Employment Type,Classification. Classification,LengthofServiceOverall. Overall Length of Service at Institute (in years),LengthofServiceCurrent. Length of Service at current workplace (in years)
0,6.341330e+17,Southern Queensland Institute of TAFE,Non-Delivery (corporate),2010.0,Contract Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Agree,Agree,Agree,Neutral,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Strongly Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Neutral,Agree,Agree,Yes,Yes,Yes,Yes,Face to Face,-,-,Face to Face,-,-,Face to Face,-,-,Yes,Yes,Yes,Yes,Yes,Female,26 30,Temporary Full-time,Administration (AO),1-2,1-2
1,6.341337e+17,Mount Isa Institute of TAFE,Non-Delivery (corporate),2010.0,Retirement,-,-,-,-,-,-,-,-,-,Travel,-,-,NaN,Agree,Agree,Agree,Agree,Agree,Strongly Agree,Strongly Agree,Agree,Strongly Agree,Agree,Agree,Agree,Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Agree,Agree,Agree,Strongly Agree,Agree,Agree,Agree,Strongly Agree,Agree,Strongly Agree,Strongly Agree,Agree,Agree,Strongly Agree,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN
2,6.341388e+17,Mount Isa Institute of TAFE,Delivery (teaching),2010.0,Retirement,-,-,-,-,-,-,-,-,-,-,-,NONE,NaN,Agree,Agree,Agree,Agree,Agree,Agree,Strongly Agree,Agree,Agree,Agree,Agree,Neutral,Neutral,Strongly Agree,Strongly Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN
3,6.341399e+17,Mount Isa Institute of TAFE,Non-Delivery (corporate),2010.0,Resignation,-,-,-,-,-,-,-,-,-,Travel,-,-,NaN,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Yes,No,Yes,Yes,-,-,-,NaN,-,-,-,-,-,Yes,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN
4,6.341466e+17,Southern Queensland Institute of TAFE,Delivery (teaching),2010.0,Resignation,-,Career Move - Private Sector,-,-,-,-,-,-,-,-,-,-,NaN,Agree,Agree,Strongly Agree,Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Agree,Strongly Agree,Strongly Agree,Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Yes,Yes,Yes,Yes,-,-,Induction Manual,Face to Face,-,-,Face to Face,-,-,Yes,Yes,Yes,Yes,Yes,Male,41 45,Permanent Full-time,Teacher (including LVT),3-4,3-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,6.350668e+17,Barrier Reef Institute of TAFE,Delivery (teaching),2013.0,Resignation,Career Move - Public Sector,-,-,-,-,-,-,-,-,-,-,-,NaN,Neutral,Agree,Agree,Neutral,Disagree,Neutral,Agree,Agree,Agree,Disagree,Agree,Agree,Agree,Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Neutral,Neutral,Neutral,Agree,Agree,Neutral,Neutral,Agree,Neutral,Neutral,Neutral,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,Yes,Yes,Male,51-55,Temporary Full-time,Teacher (including LVT),1-2,1-2
698,6.350677e+17,Southern Queensland Institute of TAFE,Non-Delivery (corporate),2013.0,Resignation,Career Move - Public Sector,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,6.350704e+17,Tropical North Institute of TAFE,Delivery (teaching),2013.0,Resignation,-,-,-,-,-,-,-,-,-,-,Other,-,NaN,Agree,Strongly Agree,Strongly Agree,Neutral,Agree,Agree,Agree,Agree,Agree,Neutral,Agree,Agree,Agree,Agree,Agree,Strongly Agree,Strongly Agree,Agree,Agree,Agree,Agree,Agree,Strongly Agree,Agree,Strongly Agree,Strongly Agree,Strongly Agree,Agree,Agree,Agree,Yes,No,Yes,Yes,-,-,-,-,-,Induction Manual,Face to Face,-,-,Yes,Yes,Yes,Yes,Yes,Female,51-55,Permanent Full-time,Teacher (including LVT),5-6,1-2
700,6.350712e+17,Southbank Institute of Technology,Non-Delivery (corporate),2013.0,Contract Expired,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Strongly Agree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Disagree,Agree,Neutral,Neutral,Strongly Agree,Agree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Agree,Strongly Agree,Neutral,Agree,Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Disagree,Strongly Disagree,Disagree,Agree,Strongly Agree,Agree,Neutral,Yes,No,Yes,Yes,-,On-line,-,Face to Face,-,-,Face to Face,-,-,No,No,No,Yes,No,Female,41 45,Temporary Full-time,Professional Officer (PO),1-2,1-2
701,6.350730e+17,Tropical North Institute of TAFE,Non-Delivery (corporate),2013.0,Resignation,-,-,Career Move - Self-employment,-,-,-,-,-,-,Travel,-,-,Career Move - Self-employment,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Neutral,Strongly Agree,Strongly Agree,Agree,Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Neutral,Strongly Agree,Strongly Agree,Yes,Yes,Yes,Yes,-,-,-,-,-,-,-,-,-,Yes,Yes,Yes,Yes,Yes,Female,26 30,Contract/casual,Administration (AO),3-4,1-2

In [7]:
del_sur.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 822 entries, 0 to 821
Data columns (total 56 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ID                                   822 non-null    int64
 1   SeparationType                       822 non-null    object
 2   Cease Date                           822 non-null    object
 3   DETE Start Date                      822 non-null    object
 4   Role Start Date                      822 non-null    object
 5   Position                             817 non-null    object
 6   Classification                       455 non-null    object
 7   Region                               822 non-null    object
 8   Business Unit                        126 non-null    object
 9   Employment Status                    817 non-null    object
 10  Career move to public sector         822 non-null    bool
 11  Career move to private sector        822 non-null    bool
 12  Interpersonal conflicts              822 non-null    bool
 13  Job dissatisfaction                  822 non-null    bool
 14  Dissatisfaction with the department  822 non-null    bool
 15  Physical work environment            822 non-null    bool
 16  Lack of recognition                  822 non-null    bool
 17  Lack of job security                 822 non-null    bool
 18  Work location                        822 non-null    bool
 19  Employment conditions                822 non-null    bool
 20  Maternity/family                     822 non-null    bool
 21  Relocation                           822 non-null    bool
 22  Study/Travel                         822 non-null    bool
 23  Ill Health                           822 non-null    bool
 24  Traumatic incident                   822 non-null    bool
 25  Work life balance                    822 non-null    bool
 26  Workload                             822 non-null    bool
 27  None of the above                    822 non-null    bool
 28  Professional Development             808 non-null    object
 29  Opportunities for promotion          735 non-null    object
 30  Staff morale                         816 non-null    object
 31  Workplace issue                      788 non-null    object
 32  Physical environment                 817 non-null    object
 33  Worklife balance                     815 non-null    object
 34  Stress and pressure support          810 non-null    object
 35  Performance of supervisor            813 non-null    object
 36  Peer support                         812 non-null    object
 37  Initiative                           813 non-null    object
 38  Skills                               811 non-null    object
 39  Coach                                767 non-null    object
 40  Career Aspirations                   746 non-null    object
 41  Feedback                             792 non-null    object
 42  Further PD                           768 non-null    object
 43  Communication                        814 non-null    object
 44  My say                               812 non-null    object
 45  Information                          816 non-null    object
 46  Kept informed                        813 non-null    object
 47  Wellness programs                    766 non-null    object
 48  Health & Safety                      793 non-null    object
 49  Gender                               798 non-null    object
 50  Age                                  811 non-null    object
 51  Aboriginal                           16 non-null     object
 52  Torres Strait                        3 non-null      object
 53  South Sea                            7 non-null      object
 54  Disability                           23 non-null     object
 55  NESB                                 32 non-null     object
dtypes: bool(18), int64(1), object(37)
memory usage: 258.6+ KB

In [8]:
print("DETE Survey Data:")
print(f"Number of columns: {len(del_sur.columns)}")
print("Data types of columns:")
print(del_sur.dtypes)

print("\nTAFE Survey Data:")
print(f"Number of columns: {len(tafe_sur.columns)}")
print("Data types of columns:")
print(tafe_sur.dtypes)

DETE Survey Data:
Number of columns: 56
Data types of columns:
ID                                      int64
SeparationType                         object
Cease Date                             object
DETE Start Date                        object
Role Start Date                        object
Position                               object
Classification                         object
Region                                 object
Business Unit                          object
Employment Status                      object
Career move to public sector             bool
Career move to private sector            bool
Interpersonal conflicts                  bool
Job dissatisfaction                      bool
Dissatisfaction with the department      bool
Physical work environment                bool
Lack of recognition                      bool
Lack of job security                     bool
Work location                            bool
Employment conditions                    bool
Maternity/family                         bool
Relocation                               bool
Study/Travel                             bool
Ill Health                               bool
Traumatic incident                       bool
Work life balance                        bool
Workload                                 bool
None of the above                        bool
Professional Development               object
Opportunities for promotion            object
Staff morale                           object
Workplace issue                        object
Physical environment                   object
Worklife balance                       object
Stress and pressure support            object
Performance of supervisor              object
Peer support                           object
Initiative                             object
Skills                                 object
Coach                                  object
Career Aspirations                     object
Feedback                               object
Further PD                             object
Communication                          object
My say                                 object
Information                            object
Kept informed                          object
Wellness programs                      object
Health & Safety                        object
Gender                                 object
Age                                    object
Aboriginal                             object
Torres Strait                          object
South Sea                              object
Disability                             object
NESB                                   object
dtype: object

TAFE Survey Data:
Number of columns: 72
Data types of columns:
Record ID                                                                    float64
Institute                                                                     object
WorkArea                                                                      object
CESSATION YEAR                                                               float64
Reason for ceasing employment                                                 object
                                                                              ...
CurrentAge. Current Age                                                       object
Employment Type. Employment Type                                              object
Classification. Classification                                                object
LengthofServiceOverall. Overall Length of Service at Institute (in years)     object
LengthofServiceCurrent. Length of Service at current workplace (in years)     object
Length: 72, dtype: object

### Task 2 (1 mark)

You should be able to make the following observation based on the work you did above in Task 1:
  - The __dete_survey__ dataframe contains `'Not Stated'` values that indicate values are missing, but they aren't represented as `NaN`.
  
Read the dataset __dete_survey.csv__ again such that the `'Not Stated'` values are replaced with NaN ensuring that the mechanism for representing missing values is consistent across the dataset.

<u>Hint:</u> Use the __na_values__ argument in __pd.read_csv__

In [11]:
### Write your code below this comment.
dete_survey = pd.read_csv("dete_survey.csv", na_values='Not Stated')
dete_survey.head()

,ID,SeparationType,Cease Date,DETE Start Date,Role Start Date,Position,Classification,Region,Business Unit,Employment Status,Career move to public sector,Career move to private sector,Interpersonal conflicts,Job dissatisfaction,Dissatisfaction with the department,Physical work environment,Lack of recognition,Lack of job security,Work location,Employment conditions,Maternity/family,Relocation,Study/Travel,Ill Health,Traumatic incident,Work life balance,Workload,None of the above,Professional Development,Opportunities for promotion,Staff morale,Workplace issue,Physical environment,Worklife balance,Stress and pressure support,Performance of supervisor,Peer support,Initiative,Skills,Coach,Career Aspirations,Feedback,Further PD,Communication,My say,Information,Kept informed,Wellness programs,Health & Safety,Gender,Age,Aboriginal,Torres Strait,South Sea,Disability,NESB
0,1,Ill Health Retirement,08/2012,1984.0,2004.0,Public Servant,A01-A04,Central Office,Corporate Strategy and Peformance,Permanent Full-time,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,True,A,A,N,N,N,A,A,A,A,N,N,N,A,A,A,N,A,A,N,N,N,Male,56-60,NaN,NaN,NaN,NaN,Yes
1,2,Voluntary Early Retirement (VER),08/2012,NaN,NaN,Public Servant,AO5-AO7,Central Office,Corporate Strategy and Peformance,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,A,A,N,N,N,N,A,A,A,N,N,N,A,A,A,N,A,A,N,N,N,Male,56-60,NaN,NaN,NaN,NaN,NaN
2,3,Voluntary Early Retirement (VER),05/2012,2011.0,2011.0,Schools Officer,NaN,Central Office,Education Queensland,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,A,A,N,N,N,N,Male,61 or older,NaN,NaN,NaN,NaN,NaN
3,4,Resignation-Other reasons,05/2012,2005.0,2006.0,Teacher,Primary,Central Queensland,NaN,Permanent Full-time,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,A,N,N,N,A,A,N,N,A,A,A,A,A,A,A,A,A,A,A,N,A,Female,36-40,NaN,NaN,NaN,NaN,NaN
4,5,Age Retirement,05/2012,1970.0,1989.0,Head of Curriculum/Head of Special Education,NaN,South East,NaN,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,A,A,N,N,D,D,N,A,A,A,A,A,A,SA,SA,D,D,A,N,A,M,Female,61 or older,NaN,NaN,NaN,NaN,NaN

### Task 3 (1 mark)

Both the __dete_survey__ and __tafe_survey__ contain many columns that we don't need to complete our analysis.

Drop columns 28-48 (inclusive of both ends) in __dete_survey__  as well as columns 17-65 in __tafe_survey__ and save the resulting dataframes as __dete_survey_updated__ and __tafe_survey_updated__ respectively. Also confirm that the number of columns in the new dataframes is less by 21 and 49 respectively compared with the original dataframes.

In [12]:
### Write your code below this comment.
dete_survey_updated = dete_survey.drop(dete_survey.columns[28:49], axis=1)
tafe_survey_updated = tafe_sur.drop(tafe_sur.columns[17:66], axis=1)

In [20]:
print(f'The shape of dete_survey before was {dete_survey.shape} and for tafe_survey was {tafe_sur.shape}')
print(f'\nThe new shape after drop of dete_survey before is {dete_survey_updated.shape} and for tafe_survey is {tafe_survey_updated.shape}')

The shape of dete_survey before was (822, 56) and for tafe_survey was (702, 72)

The new shape after drop of dete_survey before is (822, 35) and for tafe_survey is (702, 23)

### Task 4 (2 marks)

Rename all the columns in the dataframe __dete_survey_updated__ such that the following requirements are satisfied:

1. The column names are in lower case
2. Any leading and trailing spaces are removed from column names
3. Any space in column names is replaced with an underscore ( _ )

Also, rename the columns in the dataframe __tafe_survey_updated__ such that they match the names in __dete_survey_updated__. You can use the following dictionary for mapping:

    {'Record ID': 'id', 'CESSATION YEAR': 'cease_date', 'Reason for ceasing employment': 'separationtype',
    'Gender. What is your Gender?': 'gender', 'CurrentAge. Current Age': 'age',
    'Employment Type. Employment Type': 'employment_status', 'Classification. Classification': 'position',
    'LengthofServiceOverall. Overall Length of Service at Institute (in years)': 'institute_service',
    'LengthofServiceCurrent. Length of Service at current workplace (in years)': 'role_service'}

In [21]:
### Write your code below this comment.
dete_survey_updated.head(0)

Empty DataFrame
Columns: [ID, SeparationType, Cease Date, DETE Start Date, Role Start Date, Position, Classification, Region, Business Unit, Employment Status, Career move to public sector, Career move to private sector, Interpersonal conflicts, Job dissatisfaction, Dissatisfaction with the department, Physical work environment, Lack of recognition, Lack of job security, Work location, Employment conditions, Maternity/family, Relocation, Study/Travel, Ill Health, Traumatic incident, Work life balance, Workload, None of the above, Gender, Age, Aboriginal, Torres Strait, South Sea, Disability, NESB]
Index: []

In [23]:
dete_survey_updated.columns = dete_survey_updated.columns.str.lower().str.strip().str.replace(' ', '_')

In [24]:
### Write your code below this comment.
dete_survey_updated.head(0)

Empty DataFrame
Columns: [id, separationtype, cease_date, dete_start_date, role_start_date, position, classification, region, business_unit, employment_status, career_move_to_public_sector, career_move_to_private_sector, interpersonal_conflicts, job_dissatisfaction, dissatisfaction_with_the_department, physical_work_environment, lack_of_recognition, lack_of_job_security, work_location, employment_conditions, maternity/family, relocation, study/travel, ill_health, traumatic_incident, work_life_balance, workload, none_of_the_above, gender, age, aboriginal, torres_strait, south_sea, disability, nesb]
Index: []

In [25]:
tafe_survey_updated .head(0)

Empty DataFrame
Columns: [Record ID, Institute, WorkArea, CESSATION YEAR, Reason for ceasing employment, Contributing Factors. Career Move - Public Sector , Contributing Factors. Career Move - Private Sector , Contributing Factors. Career Move - Self-employment, Contributing Factors. Ill Health, Contributing Factors. Maternity/Family, Contributing Factors. Dissatisfaction, Contributing Factors. Job Dissatisfaction, Contributing Factors. Interpersonal Conflict, Contributing Factors. Study, Contributing Factors. Travel, Contributing Factors. Other, Contributing Factors. NONE, Gender. What is your Gender?, CurrentAge. Current Age, Employment Type. Employment Type, Classification. Classification, LengthofServiceOverall. Overall Length of Service at Institute (in years), LengthofServiceCurrent. Length of Service at current workplace (in years)]
Index: []

In [26]:
col_map = {
    'Record ID': 'id',
    'CESSATION YEAR': 'cease_date',
    'Reason for ceasing employment': 'separationtype',
    'Gender. What is your Gender?': 'gender',
    'CurrentAge. Current Age': 'age',
    'Employment Type. Employment Type': 'employment_status',
    'Classification. Classification': 'position',
    'LengthofServiceOverall. Overall Length of Service at Institute (in years)': 'institute_service',
    'LengthofServiceCurrent. Length of Service at current workplace (in years)': 'role_service'
}

tafe_survey_updated = tafe_survey_updated.rename(columns=col_map)

tafe_survey_updated.head(0)

Empty DataFrame
Columns: [id, Institute, WorkArea, cease_date, separationtype, Contributing Factors. Career Move - Public Sector , Contributing Factors. Career Move - Private Sector , Contributing Factors. Career Move - Self-employment, Contributing Factors. Ill Health, Contributing Factors. Maternity/Family, Contributing Factors. Dissatisfaction, Contributing Factors. Job Dissatisfaction, Contributing Factors. Interpersonal Conflict, Contributing Factors. Study, Contributing Factors. Travel, Contributing Factors. Other, Contributing Factors. NONE, gender, age, employment_status, position, institute_service, role_service]
Index: []

In [29]:
#keeping it same as dete_survey to remove any extra spaces, truncate them and add '_'
tafe_survey_updated.columns = tafe_survey_updated.columns.str.lower().str.strip().str.replace(' ', '_')
tafe_survey_updated.columns = tafe_survey_updated.columns.str.replace('.', '').str.replace('-', '')

<ipython-input-29-05c21f1d1ba1>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  tafe_survey_updated.columns = tafe_survey_updated.columns.str.replace('.', '').str.replace('-', '')

In [30]:
tafe_survey_updated.head(0)

Empty DataFrame
Columns: [id, institute, workarea, cease_date, separationtype, contributing_factors_career_move__public_sector, contributing_factors_career_move__private_sector, contributing_factors_career_move__selfemployment, contributing_factors_ill_health, contributing_factors_maternity/family, contributing_factors_dissatisfaction, contributing_factors_job_dissatisfaction, contributing_factors_interpersonal_conflict, contributing_factors_study, contributing_factors_travel, contributing_factors_other, contributing_factors_none, gender, age, employment_status, position, institute_service, role_service]
Index: []

### Task 5 (2 marks)

Get the counts for all the unique values in the ```'separationtype'``` column of both the dataframes __tafe_survey_updated__ and __dete_survey_updated__. You may notice that there is a single value with the name 'Resignation' in __tafe_survey_updated__ while there are multiple values including the word 'Resignation' in __dete_survey_updated__.

Update the ```'separationtype'``` column in __dete_survey_updated__ such that any value that contains the word 'Resignation' is replaced with 'Resignation'. For example, 'Resignation-Other reasons' should be replaced with 'Resignation' etc.

<u>Hint:</u> All values that include the word 'Resignation' also include a hyphen (-). You can use this fact to quickly update the values.

Once you have done that, create two new updated dataframes __dete_resignations__ and __tafe_resignations__ which copy the dataframes __dete_survey_updated__ and __tafe_survey_updated__ respectively with the condition that the ```'separationtype'``` column in both the source dataframes equals the value 'Resignation'.

In [39]:
tafe_survey_updated['separationtype'].value_counts()

Resignation                 340
Contract Expired            127
Retrenchment/ Redundancy    104
Retirement                   82
Transfer                     25
Termination                  23
Name: separationtype, dtype: int64

In [38]:
dete_survey_updated['separationtype'].value_counts()

Age Retirement                          285
Resignation-Other reasons               150
Resignation-Other employer               91
Resignation-Move overseas/interstate     70
Voluntary Early Retirement (VER)         67
Ill Health Retirement                    61
Other                                    49
Contract Expired                         34
Termination                              15
Name: separationtype, dtype: int64

In [42]:
dete_survey_updated['separationtype'].str.split('-').str[0]

0                 Ill Health Retirement
1      Voluntary Early Retirement (VER)
2      Voluntary Early Retirement (VER)
3                           Resignation
4                        Age Retirement
                     ...
817                      Age Retirement
818                      Age Retirement
819                         Resignation
820               Ill Health Retirement
821                         Resignation
Name: separationtype, Length: 822, dtype: object

In [47]:
dete_survey_updated['separationtype'].value_counts()

Resignation                         311
Age Retirement                      285
Voluntary Early Retirement (VER)     67
Ill Health Retirement                61
Other                                49
Contract Expired                     34
Termination                          15
Name: separationtype, dtype: int64

In [48]:
dete_resignations = dete_survey_updated[dete_survey_updated['separationtype'] == 'Resignation']
tafe_resignations = tafe_survey_updated[tafe_survey_updated['separationtype'] == 'Resignation']

In [50]:
dete_separation_counts = dete_resignations['separationtype'].value_counts()
tafe_separation_counts = tafe_resignations['separationtype'].value_counts()
print(f'Separation counts for dete is {dete_separation_counts} & for tafe is {tafe_separation_counts}')

Separation counts for dete is Resignation    311
Name: separationtype, dtype: int64 & for tafe is Resignation    340
Name: separationtype, dtype: int64

### Task 6 (2 marks)

Show the counts of missing values for all the columns in the __tafe_resignations__ dataframe.

Now go ahead and first store the counts of all the unique values (including missing values) for the ```'employment_status'``` column in a variable named __es_cnts__ and then show the counts. Once you have done that, fill the missing values for the ```'employment_status'``` column using the most frequent non-NA unique value. Finally, show the counts of all the unique values (including missing values) for the ```'employment_status'``` column once again. There shouldn't be any missing values for this column now.

<u>Hint:</u> Use _idxmax()_

In [51]:
### Write your code below this comment.
print(f'Missing counts in tafe_resignations df is {tafe_resignations.isnull().sum()}')

Missing counts in tafe_resignations df is id                                                   0
institute                                            0
workarea                                             0
cease_date                                           5
separationtype                                       0
contributing_factors_career_move__public_sector      8
contributing_factors_career_move__private_sector     8
contributing_factors_career_move__selfemployment     8
contributing_factors_ill_health                      8
contributing_factors_maternity/family                8
contributing_factors_dissatisfaction                 8
contributing_factors_job_dissatisfaction             8
contributing_factors_interpersonal_conflict          8
contributing_factors_study                           8
contributing_factors_travel                          8
contributing_factors_other                           8
contributing_factors_none                            8
gender                                              50
age                                                 50
employment_status                                   50
position                                            50
institute_service                                   50
role_service                                        50
dtype: int64

In [52]:
es_cnts = tafe_resignations['employment_status'].value_counts(dropna=False)
print(f'The count for employment status before update is {es_cnts}')

The count for employment status before update is Temporary Full-time    111
Permanent Full-time     98
NaN                     50
Contract/casual         29
Temporary Part-time     27
Permanent Part-time     25
Name: employment_status, dtype: int64

In [61]:
freq_val = es_cnts.idxmax()

tafe_resignations['employment_status'].fillna(freq_val, inplace=True)

<ipython-input-61-cda074b63fec>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tafe_resignations['employment_status'].fillna(freq_val, inplace=True)

In [54]:
es_cnts_after = tafe_resignations['employment_status'].value_counts(dropna=False)
print(f'The count for employment status after update is {es_cnts_after}')

The count for employment status after update is Temporary Full-time    161
Permanent Full-time     98
Contract/casual         29
Temporary Part-time     27
Permanent Part-time     25
Name: employment_status, dtype: int64

In [62]:
print(f'Missing counts in tafe_resignations df after treatment is {tafe_resignations.isnull().sum()}')

Missing counts in tafe_resignations df after treatment is id                                                   0
institute                                            0
workarea                                             0
cease_date                                           5
separationtype                                       0
contributing_factors_career_move__public_sector      8
contributing_factors_career_move__private_sector     8
contributing_factors_career_move__selfemployment     8
contributing_factors_ill_health                      8
contributing_factors_maternity/family                8
contributing_factors_dissatisfaction                 8
contributing_factors_job_dissatisfaction             8
contributing_factors_interpersonal_conflict          8
contributing_factors_study                           8
contributing_factors_travel                          8
contributing_factors_other                           8
contributing_factors_none                            8
gender                                              50
age                                                 50
employment_status                                    0
position                                            50
institute_service                                   50
role_service                                        50
dtype: int64